name: FTP Deploy
on:
  push:
    branches:
      - main
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4  # Updated to latest version
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/  # Most common for shared hosting
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/