name: FTP Deploy

on:
  push:
    branches:
      - main # or the branch you want to deploy from

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}    # FTP server (e.g., ftp.example.com)
          username: ${{ secrets.FTP_USERNAME }} # FTP username
          password: ${{ secrets.FTP_PASSWORD }} # FTP password
          local-dir: ./  # Directory to deploy, adjust if needed
          server-dir: /path/on/server/ # Remote directory on the server

